#!/bin/bash

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
repo_root=$(CDPATH= cd -- "$script_dir/../.." && pwd)
appdir="$script_dir"
dce_dir="$repo_root/ns-3-dce"

#echo $#
if [ $# -lt 4 ]; then
   echo "Error! You must run:"
   echo "   ./run_simulations <times> <nrelays> <nclients> <dest>"
   echo
   exit 1
fi

#count=0
#for a in $*; do
#   count=`expr $count + 1`
#   echo "Argument $count: $a" 
#done

max=$1;
nrelays=$2
nclients=$3
dest=$4
echo "Starting $max simulations..."
echo "Command: ./waf --run \"dce-gmtp-master --nrelays=$nrelays --nclients=$nclients\""

i=1
cd "$dce_dir"
while [ $i -le $max ]
do
    echo "Running $i of $max simulations"
    ./waf --run "dce-gmtp-master --nrelays=$nrelays --nclients=$nclients"
    i=`expr $i + 1`
done

cd "$appdir"
./copy_results $dest

cd "$dce_dir"
rm -rf files-* *.pcap *.tr
cd "$appdir"
echo
