#!/bin/bash

pre=0

if [ $# -gt 1 ]; then
   echo "Error! You must run:"
   echo "   ./run_all <pre>"
   exit 1
elif [ $# -eq 1 ]; then
    pre=1
fi

if [ $pre=1 ]; then
    ./run_simulation 10 1 1 pre-1
    ./run_simulation 10 1 10 pre-2
    ./run_simulation 10 1 20 pre-3
    
    ./run_simulation 10 3 1 pre-4
    ./run_simulation 10 3 10 pre-5
    ./run_simulation 10 3 20 pre-6
    
else
    ./run_simulation 16 1 1 sim-1
    ./run_simulation 18 1 10 sim-2
    ./run_simulation 34 1 20 sim-3

    ./run_simulation 18 3 1 sim-4
    ./run_simulation 25 3 10 sim-5
    ./run_simulation 50 3 20 sim-6
fi

echo
exit(0)
